### ISSUE TITLE
Type Declarations Not Found

### ISSUE THREAD

**Issue by princefishthrower** [FullStackCraft/react-native-keyboard-shift#1]
As the title states, the current arrangement of this package, the type declarations cannot be found:

```
Cannot find module '@fullstackcraft/react-native-keyboard-shift' or its corresponding type declarations.
```

This error can be immediately seen in `example/App.tsx`, after installing all dependencies.

**Comment by TheRogue76** [comment]
As far as i can tell there are a couple of things at play. 1) The package.json file is looking for index.js at the root directory (the ```"main"``` attribute is pointing to it) and once it fails it throws out this error. 2) The package needs ```@react-native-community/hooks``` and ```@react-navigation/elements``` so maybe we should move them to dependencies instead of devDependency.

I think we can go with [this tutorial](https://itnext.io/step-by-step-building-and-publishing-an-npm-typescript-package-44fe7164964c) for setting up tsc and other linting and testing methodologies (seemed to cover all the bases pretty well).

At the moment i'm having trouble running the example project (It's on RN 0.66 and for some reason XCode 13 seems to switch between compiling and not compiling at the drop of the hat). I'll report back as soon as i can this up and running. 

Cheers

**Comment by TheRogue76** [comment]
I propose we get this up and running on TypeScript only (files being tsx and ts) and then slowly add compiling to commonJs and es modules afterwards with TSC. This way we can make sure what we are dealing with at each moment instead of working on several things at once

**Comment by princefishthrower** [comment]
@TheRogue76 - added a lot of the tooling here, there is a new error now: `Can't find variable: React`

**Comment by TheRogue76** [comment]
That issue is happening due to the package needing React and React-Native when trying to compile with tsc. I managed to get the example app running but it crashes when not inside a Stack Navigator as ```useHeaderHeight``` does not exist.

I made two optional fields: ```hasHeader``` and ```headerOffset```. In case the user is not using stack navigator they can ignore ```hasHeader``` and if they are they can set it to ```true```, at which point ```useHeaderHeight``` can be imported. The ```headerOffset``` is in case they decide to assign another value and can be assigned any number.

Please publish the package again under 1.1.3 so we can run tests on example. I have a good feeling about this build

**Comment by TheRogue76** [comment]
@princefishthrower sent to you. The build now runs on the example project but the ```keyboardDidShow``` and ```keyboardDidHide``` events are not being triggered (i put a console log in both handlers. No logs were created). Needs further assessment. I'll update as soon as i have something.

**Comment by TheRogue76** [comment]
The package now runs on both iOS and Android and the optional flags work on iOS in the example app. It has been tagged as 1.1.4. Moving on to increasing testing coverage.
